// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (body, user_id)
VALUES ($1, $2)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateMessageParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.Body, arg.UserID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, created_at, updated_at, body, user_id
FROM messages
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const getMessages_CreatedAtASC = `-- name: GetMessages_CreatedAtASC :many
SELECT id, created_at, updated_at, body, user_id
FROM messages
ORDER BY created_at ASC
`

func (q *Queries) GetMessages_CreatedAtASC(ctx context.Context) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessages_CreatedAtASC)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
